---
- name: Installed required packages
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name:
      - fontconfig
      - openjdk-11-jre
    state: present

- name: Create the Jenkins home folder
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /home/jenkins
    state: directory
  register: folder_created

- name: Print a message if home folder was created
  ansible.builtin.debug:
    msg: "Folder '{{ folder_created.path }}' has been created."
  when: folder_created.changed

- name: Change jenkins home folder permissions
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /home/jenkins
    mode: '0777'
  when: folder_created.changed

- name: Ensure python3.10 is installed
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name: python3.10
    state: present

- name: Ensure python3-pip is installed
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name: python3-pip
    state: present

- name: Install python3.10 virtualenv
  become: yes
  become_method: sudo
  apt:
    name: python3.10-venv
    state: present


- name: Install aptitude
  become: yes
  become_method: sudo
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install Docker required system packages
  become: yes
  become_method: sudo
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  become: yes
  become_method: sudo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  become_method: sudo
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  become: yes
  become_method: sudo
  pip:
    name: docker