---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes_flux_jenkins_github
